server:
#  port: ${SERVER_PORT}
  port: 9000
spring:
  application:
    name: gateway-service
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enable Eureka integration: Auto-detect services from Eureka
      routes:
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/user/**, /api/v1/admin/**


        - id: ITEM-SERVICE
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/api/v1/items/**


        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**


#        - id: SWAGGER
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/api/orders/**

eureka:
  client:
    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
       defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: WARN