spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
#    bootstrap-servers: localhost:9091

  application:
    name: flashsale-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
#      host: localhost
#      port: 6379

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
#      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: ${SERVER_PORT}
#  port: 8086

