spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

#  cassandra:
#    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS}
#    port: ${SPRING_CASSANDRA_PORT}
#    keyspace-name: ${SPRING_CASSANDRA_KEYSPACE}
#    local-datacenter: datacenter1
#    schema-action: CREATE_IF_NOT_EXISTS
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:mysql://localhost:3306/emart_order?useSSL=false&serverTimezone=UTC
#    username: root
#    password: ying1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
#      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
    port: ${SERVER_PORT}
#  port: 8082

resilience4j.circuitbreaker:
  instances:
    createOrder:
      failureRateThreshold: 50  # Open circuit when 50% of requests fail
      slowCallRateThreshold: 60  # Open circuit if 60% of calls are slow
      slowCallDurationThreshold: 2s  # Calls taking more than 2 seconds are considered slow
      waitDurationInOpenState: 5s  # Time before Circuit Breaker moves to half-open state
      permittedNumberOfCallsInHalfOpenState: 3  # Number of calls allowed in half-open state
      maxWaitDurationInHalfOpenState: 2s  # Wait time in half-open state
      slidingWindowType: COUNT_BASED  # COUNT_BASED or TIME_BASED
      slidingWindowSize: 10  # Number of calls to monitor for Circuit Breaker state
      ignoreExceptions:
        - com.chuwa.orderservice.exception.EmptyCartException
        - com.chuwa.orderservice.exception.ResourceNotFoundException
        - com.chuwa.orderservice.exception.InsufficientStockException
